### ISSUE TITLE
[Feature] 경기 참여 신청 Form 원형

### ISSUE THREAD

**Issue by ShangBinLee** [Team-CMD/NowKick#23]
# Dead Line

__2023-01-04 오후 내로 완성해주세요__

## 기능 요약

경기 정보 페이지에서 경기 참여 신청을 하기 위한 입력 Form이다.

로그인 기능이 아직 구현되지 않았으므로 임시로 경기 참여 신청 기능을 구현 해야한다. 따라서, 참여할 유저의 정보를 입력 받고 해당 정보를 서버로 보낼 Form이 필요하다

- Form이 입력 받아야 하는 정보 목록, Input Type, 제약 사항

    1. name(type : text)
    2. stuid(type : number)
    3. department(select box, values : [ AI융합학과, 간호학과, 경영정보학과, 경영학과, 경제학과, 경찰학과, 빅데이터응용학과, 사학과, 사회복지학과, 사회적경제기업학과, 전기전자공학과, 정보통신공학과, 정치ㆍ언론학과, 중국경제통상학과, 컴퓨터공학과 ])
    4. grade(type : number, min : 1, max : 10)
    5. gender(select box, values : [ 남, 여 ])

- Form 구성

    1. Form에 대한 안내문(개발자 판단에 따라 유동적으로 포함 여부 결정)
    2. Form(action, method 필요. method는 post로 고정)
    3. 유저 정보를 입력 받기 위한 input
    4. submit button

### 후보 1

- 행위자

    1. 사용자

- 전제 조건

    1. 사용자는 유효한 경기 정보 페이지에 접속한다
    2. '경기 참여' 버튼을 클릭하여 경기 참여 신청 Form을 불러온다

- 유스 케이스

    1. 사용자는 경기 참여 신청 Form의 모든 양식에 요구되는 값을 적절하게 입력한다
    2. 모든 양식을 내용으로 채운 상태에서 Submit Button을 클릭한다
    3. 서버에 경기 참여 신청 요청이 전송된다

- 후행 조건

    1. 경기 참여 신청 요청 처리 결과를 확인할 수 있는 페이지로 Redirect 된다(PRG 패턴)

### 후보 2

- 전제 조건

    1. 사용자는 유효한 경기 정보 페이지에 접속한다
    2. 경기 정보 페이지 최하단부에 이미 경기 참여 신청 Form이 존재한다

- 유스 케이스

후보 1의 유스케이스와 동일

- 후행 조건

마찬가지로 동일

## 제약사항

1. Form의 action은 아무 url이나 대입한다
2. method는 __'post'__ 으로 고정한다
3. input의 형식이나 속성은 정해진 대로 구현한다
4. 디자인이나 레이아웃은 레퍼런스를 참고한다
5. 각 입력 폼이 어떠한 정보에 관한 것인지 확실히 알 수 있도록 구현한다
6. 각 입력 폼의 width는 동일하게 설정한다
7. submit button의 내용은 경기 참여 신청을 서버에 보내는 버튼이라는 것을 알 수 있도록 알아서 정한다

## 참고 템플릿

https://colorlib.com/etc/cf/ContactFrom_v16/index.html

**Comment by jangjuntae** [comment]
후보 2번 선택
