### ISSUE TITLE
[Fix] 서버 애플리케이션 실행 시 db 연결 에러

### ISSUE THREAD

**Issue by ShangBinLee** [Team-CMD/NowKick#9]
## 관련 이슈

- #3 

## 의도한 동작

npm run dev-start를 통한 서버 애플리케이션 실행 시, mysql db에 해당하는 계정으로 정상적으로 연결되는 것, 그리고 db 관련 동작이 정상적으로 수행되는 것을 기대하였다.

## 현재 동작

npm run dev-start를 통한 실행 시 서버는 정상적으로 구동되는 것처럼 보이지만 db와 연결하고 쿼리를 하는 /example 경로를 통해 사이트에 접속했을 때, node.js에서 db에 대한 연결이 거부되었다는 에러와 함께 정상적으로 요청이 처리되지 않고 클라이언트에서는 응답을 받지 못한다.

## 재현을 위한 코드

[당시 상황을 보존한 브랜치](https://github.com/Team-CMD/NowKick/tree/issue_9)

## 재현 방법

- 정상적으로 프로젝트 설치가 끝난 상태에서
    1. npm run dev-start
    2. 브라우저, Postman 등의 API test tool을 이용하여 localhost:3000/example 접속

## 관련 로그

```
C:\projects\We_Don't_Know_Code\NowKick\node_modules\mysql2\lib\packets\packet.js:728
    const err = new Error(message);
                ^

Error: Access denied for user ''@'localhost' (using password: NO)
    at Packet.asError (C:\projects\We_Don't_Know_Code\NowKick\node_modules\mysql2\lib\packets\packet.js:728:17)
    at ClientHandshake.execute (C:\projects\We_Don't_Know_Code\NowKick\node_modules\mysql2\lib\commands\command.js:29:26)       
    at PoolConnection.handlePacket (C:\projects\We_Don't_Know_Code\NowKick\node_modules\mysql2\lib\connection.js:456:32)        
    at PacketParser.onPacket (C:\projects\We_Don't_Know_Code\NowKick\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (C:\projects\We_Don't_Know_Code\NowKick\node_modules\mysql2\lib\packet_parser.js:75:16)        
    at Socket.<anonymous> (C:\projects\We_Don't_Know_Code\NowKick\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  sqlMessage: "Access denied for user ''@'localhost' (using password: NO)",
  sql: undefined
}
```

## 문제 원인

1. 로그를 보면 ''@'localhost' 부분에서 전자의 ''에 해당하는 것이 Mysql 계정인데, 계정이 주어지지 않은 상태로 연결을 시도하였다.
2. 또한 로그에는 using password가 No로 되어있는데, 이 또한 계정에 대한 비밀번호가 주어지지 않은 상태로 연결을 시도하였기 때문에 발생한 로그이다.
3. 현재 서버 애플리케이션 실행시 import 하는 db_helper.js 모듈 내에서 process.env를 통해 계정, 비밀번호, 데이터베이스명을 해당하는 환경 변수로부터 받아오는데, 현재 상태에서는 db_helper.js에서 process.env에 접근할 때는 해당하는 환경 변수가 설정되지 않은 상태여서 DB에 연결할 때도 잘못된 연결 시도로 에러가 발생하는 것으로 확인되었다.

- 현재 main.js에서의 module import 순서(중복 import는 제외)

```
                                           main.js
                                              |
   -----------------------------------------  | ----------------------------
   |                                          |                            |
express                             ./router/example.js             ./lib/env_config.js
                                              |
                               ../db/select_as_field_from.js
                                              |
                                              |
                                       ./db_helper.js
```

js, node.js esm은 module을 후위순회의 방식으로 로드하고, 실행시키기 때문에

```
./db_helper.js -> ../db/select_as_field_from.js -> ./router/example.js -> ./lib/env_config.js
```
의 순으로 모듈이 실행되어서 처음 db_helper.js 모듈을 실행했을 때는 process.env에 DB 관련 환경 변수가 설정되지 않은 상태일 수밖에 없었다.

## 문제 해결 방법 후보

1. db_helper.js에서 정적으로 env_config.js를 import 한다
2. db 관련 처리, 동작을 하는 router에서 정적으로 env_config.js를 import 한다
3. main.js에서 env_config.js를 가장 처음으로 import 한다
4. 그 외의 여러가지 방법들

## 선정된 문제 해결 방법

3번의 방법으로 문제를 해결하기로 하였다

## 선정 이유

1, 2 번과 그 외의 방법은 근본적인 해결책이 되지 않는다고 판단했다. env_config.js 모듈은 서버 애플리케이션 시작 시에 처음에만 환경 변수를 초기화하기 위해 사용하는 모듈이지 그것으로부터 어떠한 값이나 동작 등을 가져와 재사용하기 위한 모듈이 아니다. 그러므로 1, 2번의 방법과 같이 환경 변수가 필요한 곳에서 필요할 때마다 모듈을 import하는 것은 무효하고 의도와 맞지 않는 사용법이라고 판단했다.

또한 환경 변수는 db 연결 등을 위해서만 사용되는 것이 아니기 때문에 추후의 용도 변경까지 고려해봤을 때 main.js에서 명시적으로 처음에 import하는 것이 옳다고 판단했다. 또, dotenv 모듈은 express와 별개로 동작하기 때문에 express보다도 더 먼저 import하는 게 적절하다.

**Comment by Byunjihun** [comment]
이해하기 쉽게 정리 잘하셨네요. 잘 봤습니다.
